### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by hugeblank** [swaywm/swaywm.org#11]
not a code issue I just genuinely don't know a better place to report to besides maybe irc. Doesn't look like the content of the site is in this repo either which is a real bummer

**Comment by emersion** [comment]
Yeah, see https://outage.sr.ht/. Closing because nothing can be done from the Sway side.

**Comment by WhyNotHugo** [comment]
> Doesn't look like the content of the site is in this repo either which is a real bummer

It’s all in this repo. The site is mostly a landing page, the documentation is in the man pages and wiki.
