### ISSUE TITLE
No license found

### ISSUE THREAD

**Issue by JacksonChen666** [swaywm/swaywm.org#9]
This project does not seem to have a license declared in an obvious way, or at all. A license should be added (as this project seems to be intended as open source) so that users can run, modify, study, distribute, and use the code.

https://choosealicense.com/no-permission/

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/swaywm.org/commit/b9f5611f836f91e8e0abb0eff00671b964c017f5.
